### ISSUE TITLE
Vector tile layers - error handling

### ISSUE THREAD

**Issue by alecarn** [infra-geo-ouverte/igo2-lib#1528]
The error handling not seem to be implemented. 
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/133774929/b7888082-6337-458f-8972-7a332099e8e5)

The error on local
vectortile-layer.ts:118 ERROR TypeError: Cannot read properties of undefined (reading 'call')
    at xhr.onerror [as __zone_symbol__ON_PROPERTYerror] (vectortile-layer.ts:120:17)
    at XMLHttpRequest.wrapFn (zone.umd.js:810:43)
    at _ZoneDelegate.invokeTask (zone.umd.js:445:35)
    at core.mjs:10757:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:10757:36)
    at _ZoneDelegate.invokeTask (zone.umd.js:444:64)
    at Object.onInvokeTask (core.mjs:11070:33)
    at _ZoneDelegate.invokeTask (zone.umd.js:444:64)
    at Zone.runTask (zone.umd.js:210:51)
    at ZoneTask.invokeTask [as invoke] (zone.umd.js:527:38)

To replicate: 
- Run the demo in local
- In the context panel choose "Divers format à titre d'exemple"
- Move on the map and the error should appear

**Comment by aziz-access** [comment]
i get this bug


![Image](https://github.com/infra-geo-ouverte/igo2-lib/assets/119948730/beb868af-f5fb-4793-9e6a-a1f89ca0e8ee)
